# Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  # H2 Console
  h2:
    console:
      enabled: true

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.drawsteel: DEBUG
    org.springframework.security: DEBUG
