spring:
  application:
    name: draw-steel-backend
  
  datasource:
    url: jdbc:h2:mem:drawsteeldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.drawsteel: DEBUG
    org.springframework.security: DEBUG
