# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drawsteeldb
    driver-class-name: org.postgresql.Driver
    username: drawsteel
    password: drawsteel123
  
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # H2 Console (disabled for production)
  h2:
    console:
      enabled: false

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.drawsteel: INFO
